/**
 * Dev-only generator: turns the workflow's icon JSON into components/icons.tsx.
 *
 * Kept as a script rather than done by hand so the whole suite stays provably
 * consistent — every icon goes through the same validation gate and the same
 * wrapper, so no single icon can drift off-spec.
 *
 *   npx tsx tmp/build-icons.ts <icons.json>
 */
import fs from "node:fs/promises";

type Icon = { name: string; pascal: string; keywords: string[]; body: string };

const ALLOWED_TAGS = new Set(["path", "circle", "rect", "line", "polyline", "ellipse"]);
const BANNED = [
  { re: /<g[\s>]/i, msg: "uses <g>" },
  { re: /<text[\s>]/i, msg: "uses <text>" },
  { re: /<defs[\s>]/i, msg: "uses <defs>" },
  { re: /transform=/i, msg: "uses transform" },
  { re: /style=/i, msg: "uses inline style" },
  { re: /#[0-9a-f]{3,8}\b/i, msg: "hardcodes a hex colour" },
  { re: /\b(?:rgb|hsl)a?\(/i, msg: "hardcodes a colour function" },
  { re: /stroke-width=/i, msg: "overrides stroke-width" },
  { re: /class(?:Name)?=/i, msg: "sets a class" },
];

/** SVG attributes that differ in JSX. */
const ATTR_MAP: Record<string, string> = {
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-width": "strokeWidth",
  "stroke-dasharray": "strokeDasharray",
  "stroke-miterlimit": "strokeMiterlimit",
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
  "stroke-opacity": "strokeOpacity",
  "fill-opacity": "fillOpacity",
};

function toJsx(body: string): string {
  let out = body;
  for (const [kebab, camel] of Object.entries(ATTR_MAP)) {
    out = out.replaceAll(`${kebab}=`, `${camel}=`);
  }
  // Self-close bare tags so JSX is happy.
  return out.replace(/<(path|circle|rect|line|polyline|ellipse)([^>]*?)(?<!\/)>/g, "<$1$2 />");
}

function validate(icon: Icon): string[] {
  const errs: string[] = [];
  const { body, name, pascal } = icon;

  if (!/^[a-z0-9]+(-[a-z0-9]+)*$/.test(name)) errs.push(`name "${name}" is not kebab-case`);
  if (!/^[A-Z][A-Za-z0-9]*$/.test(pascal)) errs.push(`pascal "${pascal}" is not PascalCase`);
  if (!body.trim()) errs.push("empty body");

  for (const { re, msg } of BANNED) if (re.test(body)) errs.push(msg);

  for (const tag of body.matchAll(/<([a-zA-Z]+)/g)) {
    if (!ALLOWED_TAGS.has(tag[1])) errs.push(`disallowed element <${tag[1]}>`);
  }

  // A full-bleed rect would be a background plate — the thing we explicitly don't want.
  for (const r of body.matchAll(/<rect([^>]*)>/g)) {
    const attrs = r[1];
    const w = Number(/width="([\d.]+)"/.exec(attrs)?.[1] ?? 0);
    const h = Number(/height="([\d.]+)"/.exec(attrs)?.[1] ?? 0);
    if (w >= 23 && h >= 23) errs.push("contains a full-bleed rect (background plate)");
  }

  // Any fill other than the permitted accent dot.
  for (const f of body.matchAll(/fill="([^"]+)"/g)) {
    if (f[1] !== "currentColor" && f[1] !== "none") errs.push(`unexpected fill="${f[1]}"`);
  }

  // NOTE: no arithmetic check on raw path numbers here. Path data legitimately
  // contains negative values (relative commands like `l -1 -1`) and values well
  // outside 0..24 (an arc's x-axis-rotation, e.g. `a 4 4 85 0 1 ...`), so
  // scanning the numbers produces false rejections. Bounds are verified for
  // real by rendering — see tmp/verify-bounds.ts.

  return errs;
}

const HEADER = `/**
 * Wardrobe icon suite.
 *
 * Monoline, 24x24, drawn to match the hand-made camera / star-dollar / hanger
 * icons the app started with: uniform stroke, round caps and joins, and
 * generously rounded, soft geometry.
 *
 * Every icon is transparent and strokes with \`currentColor\`, so it inherits
 * whatever text colour surrounds it and needs no background plate. Size with
 * the \`size\` prop or a Tailwind \`h-*\`/\`w-*\` class.
 *
 *   <Camera className="h-4 w-4" />
 *   <Camera size={32} />
 *
 * GENERATED by tmp/build-icons.ts — edit the source JSON and regenerate rather
 * than hand-patching, so the whole set stays on-spec.
 */
import type { SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children"> & {
  /** Pixel size for both width and height. Ignored if you size via CSS classes. */
  size?: number | string;
};

const BASE = {
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 1.75,
  strokeLinecap: "round",
  strokeLinejoin: "round",
} as const;
`;

async function main() {
  const [inPath] = process.argv.slice(2);
  const icons = JSON.parse(await fs.readFile(inPath, "utf8")) as Icon[];

  const seenName = new Set<string>();
  const seenPascal = new Set<string>();
  const good: Icon[] = [];
  let rejected = 0;

  for (const icon of icons) {
    const errs = validate(icon);
    if (seenName.has(icon.name)) errs.push("duplicate name");
    if (seenPascal.has(icon.pascal)) errs.push("duplicate pascal");
    if (errs.length) {
      console.error(`REJECT ${icon.name}: ${errs.join("; ")}`);
      rejected++;
      continue;
    }
    seenName.add(icon.name);
    seenPascal.add(icon.pascal);
    good.push(icon);
  }

  good.sort((a, b) => a.pascal.localeCompare(b.pascal));

  const components = good
    .map(
      (i) => `
/** ${i.name} — ${i.keywords.join(", ")} */
export function ${i.pascal}({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      ${toJsx(i.body)}
    </svg>
  );
}`,
    )
    .join("\n");

  const registry = `
/** Every icon, for the gallery and for name-based lookup. */
export const ICON_REGISTRY: readonly {
  name: string;
  keywords: readonly string[];
  Component: (props: IconProps) => JSX.Element;
}[] = [
${good.map((i) => `  { name: "${i.name}", keywords: [${i.keywords.map((k) => `"${k}"`).join(", ")}], Component: ${i.pascal} },`).join("\n")}
];

export type IconName = (typeof ICON_REGISTRY)[number]["name"];
`;

  await fs.writeFile("components/icons.tsx", `${HEADER}${components}\n${registry}`);
  console.log(`\nwrote components/icons.tsx — ${good.length} icons (${rejected} rejected)`);
}

main();
