/**
 * Wardrobe icon suite.
 *
 * Monoline, 24x24, drawn to match the hand-made camera / star-dollar / hanger
 * icons the app started with: uniform stroke, round caps and joins, and
 * generously rounded, soft geometry.
 *
 * Every icon is transparent and strokes with `currentColor`, so it inherits
 * whatever text colour surrounds it and needs no background plate. Size with
 * the `size` prop or a Tailwind `h-*`/`w-*` class.
 *
 *   <Camera className="h-4 w-4" />
 *   <Camera size={32} />
 *
 * GENERATED by tmp/build-icons.ts — edit the source JSON and regenerate rather
 * than hand-patching, so the whole set stays on-spec.
 */
import type { SVGProps } from "react";

export type IconProps = Omit<SVGProps<SVGSVGElement>, "children"> & {
  /** Pixel size for both width and height. Ignored if you size via CSS classes. */
  size?: number | string;
};

const BASE = {
  viewBox: "0 0 24 24",
  fill: "none",
  stroke: "currentColor",
  strokeWidth: 1.75,
  strokeLinecap: "round",
  strokeLinejoin: "round",
} as const;

/** bag — bag, handbag, tote, purse */
export function Bag({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M6.2 10h11.6a1.4 1.4 0 0 1 1.4 1.3l.6 7.1a1.8 1.8 0 0 1-1.8 1.9H6a1.8 1.8 0 0 1-1.8-1.9l.6-7.1A1.4 1.4 0 0 1 6.2 10Z"/><path d="M8.6 10V8.2a3.4 3.4 0 0 1 6.8 0V10"/>
    </svg>
  );
}

/** brand-facebook — facebook, meta, fb */
export function BrandFacebook({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.2" y="3.2" width="17.6" height="17.6" rx="4.6"/><path d="M14.6 8.2h-1.3a1.9 1.9 0 0 0-1.9 1.9v7.7"/><path d="M9.8 12.4h4.2"/>
    </svg>
  );
}

/** brand-pinterest — pinterest, pin */
export function BrandPinterest({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.2" y="3.2" width="17.6" height="17.6" rx="4.6"/><path d="M10.4 17.8 12.6 8.4"/><path d="M9.9 11.7a3.1 3.1 0 1 1 5.9 1.9c-.6 1.5-2.4 2-3.4 1"/>
    </svg>
  );
}

/** brand-reddit — reddit, snoo, forum */
export function BrandReddit({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="12" cy="14" r="6.6"/><circle cx="9.7" cy="13.6" r=".85" fill="currentColor" stroke="none"/><circle cx="14.3" cy="13.6" r=".85" fill="currentColor" stroke="none"/><path d="M9.6 16.8a4.1 4.1 0 0 0 4.8 0"/><path d="M12 7.4v-2a1.3 1.3 0 0 1 1.3-1.3h1.4"/><circle cx="16.1" cy="4.1" r="1.35"/>
    </svg>
  );
}

/** brand-whatsapp — whatsapp, chat, message */
export function BrandWhatsapp({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M4.3 19.7 5.5 16a7.7 7.7 0 1 1 2.9 2.8Z"/><path d="M9.6 9.6c-.5 1.3.2 2.7 1.3 3.7 1 1 2.4 1.7 3.6 1.2l.7-1.5-1.7-.9-.8.8a5 5 0 0 1-1.4-1.4l.8-.8-.9-1.7Z"/>
    </svg>
  );
}

/** brand-x — twitter, x, tweet */
export function BrandX({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.2" y="3.2" width="17.6" height="17.6" rx="4.6"/><path d="m8 8 8 8"/><path d="m16 8-8 8"/>
    </svg>
  );
}

/** budget — budget, gauge, meter, remaining, limit */
export function Budget({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M6 18.4a8.5 8.5 0 1 1 12 0"/><path d="M12 12.38 8.1 8.48"/><circle cx="12" cy="12.38" r=".85" fill="currentColor" stroke="none"/>
    </svg>
  );
}

/** calendar — calendar */
export function Calendar({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.4" y="5.2" width="17.2" height="15.4" rx="3.4"/><line x1="8.2" y1="3.1" x2="8.2" y2="7.3"/><line x1="15.8" y1="3.1" x2="15.8" y2="7.3"/><line x1="3.4" y1="9.8" x2="20.6" y2="9.8"/><circle cx="12" cy="15.2" r=".85" fill="currentColor" stroke="none"/>
    </svg>
  );
}

/** camera — camera */
export function Camera({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3" y="6.7" width="18" height="13.6" rx="3.7"/><path d="M8.5 6.7 9.9 4.15a1.5 1.5 0 0 1 1.3-.75h1.6a1.5 1.5 0 0 1 1.3.75L15.5 6.7"/><path d="M5.1 6.7V6a.85.85 0 0 1 .85-.85h1.3a.85.85 0 0 1 .85.85v.4"/><circle cx="12" cy="13.3" r="4.2"/><circle cx="12" cy="13.3" r="2.05"/><circle cx="17.9" cy="9.9" r=".85" fill="currentColor" stroke="none"/>
    </svg>
  );
}

/** chart — chart */
export function Chart({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <line x1="3.6" y1="20.4" x2="20.4" y2="20.4"/><line x1="6.9" y1="13.6" x2="6.9" y2="19.4"/><line x1="12" y1="10" x2="12" y2="19.4"/><line x1="17.1" y1="6.4" x2="17.1" y2="19.4"/>
    </svg>
  );
}

/** check — done, tick, confirm, complete */
export function Check({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="m4.9 12.5 4.7 4.7L19.1 7.4"/>
    </svg>
  );
}

/** clock — clock */
export function Clock({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="12" cy="12" r="8.6"/><path d="M12 7.4V12h3.7"/>
    </svg>
  );
}

/** close — x, dismiss, cancel, clear */
export function Close({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="m6.2 6.2 11.6 11.6"/><path d="m17.8 6.2-11.6 11.6"/>
    </svg>
  );
}

/** closet — closet */
export function Closet({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M3.4 4.7H20.6"/><path d="M6.12 8.3 7.8 4.7 9.48 8.3"/><path d="M6.12 8.3H4.56L3.24 10.64L4.89 11.63L5.16 10.4V17.9a1 1 0 0 0 1 1h3.28a1 1 0 0 0 1 -1V10.4L10.71 11.63L12.36 10.64L11.04 8.3H9.48"/><path d="M6.12 8.3a1.81 1.81 0 0 0 3.36 0"/><path d="M16.9 5.8 15 7.7L14.2 18.9a1.4 1.4 0 0 0 1.4 1.4h2.6a1.4 1.4 0 0 0 1.4 -1.4L18.8 7.7Z"/>
    </svg>
  );
}

/** cloud — cloud */
export function Cloud({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M6.45 17.6a3.4 3.4 0 0 1 .5-6.7 4.8 4.8 0 0 1 9.1-1.3 4.1 4.1 0 0 1 1.3 8z"/>
    </svg>
  );
}

/** coins — coins, money, cash, currency, savings */
export function Coins({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="13.7" cy="13.9" r="5.6"/><path d="M8.15 13.2A4.4 4.4 0 1 1 13.46 8.31"/>
    </svg>
  );
}

/** download — save, export, get, get-file */
export function Download({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M12 3.9v9.9"/><path d="m8.5 10.3 3.5 3.5 3.5-3.5"/><path d="M4.5 15.8v1.9a2.5 2.5 0 0 0 2.5 2.5h10a2.5 2.5 0 0 0 2.5-2.5v-1.9"/>
    </svg>
  );
}

/** dress — dress, gown, frock */
export function Dress({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M8.4 4.6a4.6 4.6 0 0 0 7.2 0c-.2 2.2-1 4-1 5.8 0 3.2 2.2 6.4 4.2 8.8-1.4 1-4 1.4-6.8 1.4s-5.4-.4-6.8-1.4c2-2.4 4.2-5.6 4.2-8.8 0-1.8-.8-3.6-1-5.8Z"/><path d="M9.4 10.4h5.2"/>
    </svg>
  );
}

/** edit — pencil, write, rename, modify */
export function Edit({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="m4.4 19.6.86-3.5a2.2 2.2 0 0 1 .58-1.05L15.5 5.4a2.35 2.35 0 0 1 3.32 3.32l-9.65 9.66a2.2 2.2 0 0 1-1.05.58l-3.5.86Z"/><path d="m13.5 7.4 3.32 3.32"/>
    </svg>
  );
}

/** external-link — buy, shop, open, outbound, link */
export function ExternalLink({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M11.9 4.4H7.6A3.2 3.2 0 0 0 4.4 7.6v8.8a3.2 3.2 0 0 0 3.2 3.2h8.8a3.2 3.2 0 0 0 3.2-3.2v-4.3"/><path d="m11.4 12.6 8.2-8.2"/><path d="M15 4.4h4.6v4.6"/>
    </svg>
  );
}

/** eye — eye */
export function Eye({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M3.4 12C3.4 12 6.7 5.8 12 5.8s8.6 6.2 8.6 6.2-3.3 6.2-8.6 6.2S3.4 12 3.4 12Z"/><circle cx="12" cy="12" r="2.8"/>
    </svg>
  );
}

/** fall — fall */
export function Fall({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M9.5 14.6C8 9.4 12.5 4.8 18.6 5.4c.6 6.1-4 10.7-9.1 9.2Z"/><path d="M5.6 18.5 15.4 8.7"/>
    </svg>
  );
}

/** filter — funnel, refine, narrow, facets */
export function Filter({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M5.7 5.1H18.3a1.5 1.5 0 0 1 1.06 2.56L14.5 12.52a2.2 2.2 0 0 0-.6 1.5v3.7a1.4 1.4 0 0 1-1.4 1.4h-1a1.4 1.4 0 0 1-1.4-1.4V14.02a2.2 2.2 0 0 0-.6-1.5L4.64 7.66A1.5 1.5 0 0 1 5.7 5.1Z"/>
    </svg>
  );
}

/** gear — gear */
export function Gear({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M9.55 3.44A8.9 8.9 0 0 1 14.45 3.44C15.24 3.67 13.48 5.87 14.24 6.17A6.25 6.25 0 0 1 15.93 7.14C16.57 7.66 17.59 5.03 18.18 5.6A8.9 8.9 0 0 1 20.64 9.85C20.83 10.64 18.04 10.21 18.17 11.02A6.25 6.25 0 0 1 18.17 12.98C18.04 13.79 20.83 13.36 20.64 14.15A8.9 8.9 0 0 1 18.18 18.4C17.59 18.97 16.57 16.34 15.93 16.86A6.25 6.25 0 0 1 14.24 17.83C13.48 18.13 15.24 20.33 14.45 20.56A8.9 8.9 0 0 1 9.55 20.56C8.76 20.33 10.52 18.13 9.76 17.83A6.25 6.25 0 0 1 8.07 16.86C7.43 16.34 6.41 18.97 5.82 18.4A8.9 8.9 0 0 1 3.36 14.15C3.17 13.36 5.96 13.79 5.83 12.98A6.25 6.25 0 0 1 5.83 11.02C5.96 10.21 3.17 10.64 3.36 9.85A8.9 8.9 0 0 1 5.82 5.6C6.41 5.03 7.43 7.66 8.07 7.14A6.25 6.25 0 0 1 9.76 6.17Z"/><circle cx="12" cy="12" r="3"/>
    </svg>
  );
}

/** glasses — glasses, spectacles, eyewear, sunglasses */
export function Glasses({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="7.3" cy="12.9" r="3.4"/><circle cx="16.7" cy="12.9" r="3.4"/><path d="M10.6 12.4c.7-1.1 2.1-1.1 2.8 0"/><path d="M4.4 10.9 3.4 9.6"/><path d="m19.6 10.9 1-1.3"/>
    </svg>
  );
}

/** grid — grid */
export function Grid({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.5" y="3.5" width="6.9" height="6.9" rx="2.1"/><rect x="13.6" y="3.5" width="6.9" height="6.9" rx="2.1"/><rect x="3.5" y="13.6" width="6.9" height="6.9" rx="2.1"/><rect x="13.6" y="13.6" width="6.9" height="6.9" rx="2.1"/>
    </svg>
  );
}

/** hanger — hanger */
export function Hanger({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M12 6.55a1.75 1.75 0 1 1 1.75-1.75"/><path d="M9.2 9.2 12 6.65 14.8 9.2"/><path d="M9.2 9.2H6.6L4.4 13.1L7.15 14.75L7.6 12.7V19.8a1 1 0 0 0 1 1h6.8a1 1 0 0 0 1 -1V12.7L16.85 14.75L19.6 13.1L17.4 9.2H14.8"/><path d="M9.2 9.2a3.01 3.01 0 0 0 5.6 0"/>
    </svg>
  );
}

/** hat — hat, cap, headwear */
export function Hat({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M8.6 15.6c0-5.7 2.4-9.6 5.4-9.6s5.4 3.9 5.4 9.6Z"/><path d="M9 15.6c-3.3.2-5 1.1-5 1.9 0 .8 1 1.3 2.7 1.3h8.5c1.5 0 2.2-.9 2.2-3.2"/>
    </svg>
  );
}

/** heart — heart */
export function Heart({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M18.6 13.6c1.6-1.5 2.4-3 2.4-4.9A4.9 4.9 0 0 0 16.2 3.8c-1.7 0-3.2.8-4.2 2.1-1-1.3-2.5-2.1-4.2-2.1A4.9 4.9 0 0 0 3 8.7c0 1.9.8 3.4 2.4 4.9l6.6 6.6Z"/>
    </svg>
  );
}

/** link — url, chain, copy link */
export function Link({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M10.2 13.8a3.6 3.6 0 0 0 5.1 0l3.1-3.1a3.6 3.6 0 0 0-5.1-5.1l-1.4 1.4"/><path d="M13.8 10.2a3.6 3.6 0 0 0-5.1 0l-3.1 3.1a3.6 3.6 0 0 0 5.1 5.1l1.4-1.4"/>
    </svg>
  );
}

/** list — list */
export function List({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <line x1="3.8" y1="6.6" x2="5.4" y2="6.6"/><line x1="8.6" y1="6.6" x2="20.2" y2="6.6"/><line x1="3.8" y1="12" x2="5.4" y2="12"/><line x1="8.6" y1="12" x2="20.2" y2="12"/><line x1="3.8" y1="17.4" x2="5.4" y2="17.4"/><line x1="8.6" y1="17.4" x2="20.2" y2="17.4"/>
    </svg>
  );
}

/** mail — email, envelope, message */
export function Mail({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.2" y="5.4" width="17.6" height="13.2" rx="3.2"/><path d="m4.6 8.2 6.1 4.3a2.2 2.2 0 0 0 2.6 0l6.1-4.3"/>
    </svg>
  );
}

/** outerwear — outerwear, coat, jacket, overcoat */
export function Outerwear({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M8.4 6.6 5.2 8.2a1.5 1.5 0 0 0-.8 1.3v9.3q0 1.4 1.4 1.4h12.4q1.4 0 1.4-1.4V9.5a1.5 1.5 0 0 0-.8-1.3l-3.2-1.6Z"/><path d="m8.4 6.6 3.6 4 3.6-4"/><path d="M12 10.6v9.6"/>
    </svg>
  );
}

/** palette — palette */
export function Palette({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M3.1 12.2C3.1 7.3 7.2 3.2 12.3 3.2C17.5 3.2 21 6.9 21 11.3C21 14.6 18.5 16.2 16.2 16.2C14.5 16.2 13.6 17.3 14.2 18.5C14.9 20 13.7 21 12 21C7 21 3.1 17.1 3.1 12.2Z"/><circle cx="8" cy="11.4" r="1.25"/><circle cx="12.3" cy="7.7" r="1.25"/><circle cx="16.7" cy="11" r="1.25"/>
    </svg>
  );
}

/** pants — pants, trousers, jeans, bottoms */
export function Pants({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M6.6 4.2h10.8l.6 16.2h-4l-1.3-8.6Q12 10.2 11.3 11.8L10 20.4H6Z"/><path d="M6.6 6.9h10.8"/>
    </svg>
  );
}

/** piggy-bank — savings, piggy, bank, save, money */
export function PiggyBank({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <ellipse cx="11.4" cy="12.6" rx="7.1" ry="5.3"/><path d="M17.98 10.6a2 2 0 0 1 0 4"/><path d="M11.8 7.31 12.85 5.69Q13.3 5 13.85 5.63L15.4 8.22"/><path d="M8.2 10.9 11.2 10.1"/><path d="M8 17.25v2.55"/><path d="M14.2 17.47v2.33"/><circle cx="15.2" cy="11.6" r=".85" fill="currentColor" stroke="none"/>
    </svg>
  );
}

/** plus — add, new, create, plus */
export function Plus({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M12 5.5v13"/><path d="M5.5 12h13"/>
    </svg>
  );
}

/** price-drop — sale, discount, price, markdown, tag */
export function PriceDrop({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M4.5 13.17Q3.4 12 4.5 10.83L8.7 6.37Q9.8 5.2 11.4 5.2L17.3 5.2Q20.5 5.2 20.5 8.4L20.5 15.6Q20.5 18.8 17.3 18.8L11.4 18.8Q9.8 18.8 8.7 17.63Z"/><circle cx="8.2" cy="12" r=".85" fill="currentColor" stroke="none"/><path d="M14.9 8.9v6"/><path d="m12.4 12.4 2.5 2.5 2.5-2.5"/>
    </svg>
  );
}

/** rain — rain */
export function Rain({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M7.5 14.6a2.8 2.8 0 0 1 .4-5.5 3.9 3.9 0 0 1 7.4-1.1 3.3 3.3 0 0 1 1.1 6.6z"/><path d="M9.9 17.4 9 19.6"/><path d="M13.2 17.9 12.3 20.6"/><path d="M16.5 17.4 15.6 19.6"/>
    </svg>
  );
}

/** receipt — receipt, purchase, invoice, bill, order */
export function Receipt({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M5.4 20.15V5.85a2.7 2.7 0 0 1 2.7-2.7h7.8a2.7 2.7 0 0 1 2.7 2.7v14.3l-3.3-1.35-3.3 1.35-3.3-1.35z"/><path d="M8.4 8.4h7.2"/><path d="M8.4 11.9h7.2"/><path d="M8.4 15.4h4.2"/>
    </svg>
  );
}

/** refresh — reload, sync, retry, update */
export function Refresh({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M4.6 12A7.4 7.4 0 0 1 17.83 7.44l1.08 1.38"/><path d="M18.91 4.72v4.1h-4.1"/><path d="M19.4 12A7.4 7.4 0 0 1 6.17 16.56l-1.08-1.38"/><path d="M5.09 19.28v-4.1h4.1"/>
    </svg>
  );
}

/** ruler — ruler */
export function Ruler({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="2.95" y="7.7" width="18.1" height="8.6" rx="2.3"/><line x1="6.6" y1="7.7" x2="6.6" y2="11"/><line x1="10.4" y1="7.7" x2="10.4" y2="12.9"/><line x1="14.2" y1="7.7" x2="14.2" y2="11"/><line x1="18" y1="7.7" x2="18" y2="12.9"/>
    </svg>
  );
}

/** scan — scan */
export function Scan({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M8.6 3.4H6.1A2.7 2.7 0 0 0 3.4 6.1v2.5"/><path d="M15.4 3.4h2.5a2.7 2.7 0 0 1 2.7 2.7v2.5"/><path d="M20.6 15.4v2.5a2.7 2.7 0 0 1-2.7 2.7h-2.5"/><path d="M8.6 20.6H6.1a2.7 2.7 0 0 1-2.7-2.7v-2.5"/><path d="M12 8.8Q12.48 11.52 15.2 12 12.48 12.48 12 15.2 11.52 12.48 8.8 12 11.52 11.52 12 8.8Z"/>
    </svg>
  );
}

/** search — find, magnifier, lookup, browse */
export function Search({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="10.7" cy="10.7" r="6.3"/><path d="m15.3 15.3 4.2 4.2"/>
    </svg>
  );
}

/** share — send, network, refer, invite */
export function Share({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="17" cy="6.6" r="2.55"/><circle cx="6.9" cy="12" r="2.55"/><circle cx="17" cy="17.4" r="2.55"/><path d="M9.59 10.56 14.31 8.04"/><path d="M9.59 13.44 14.31 15.96"/>
    </svg>
  );
}

/** shoes — shoes, sneaker, footwear, trainers */
export function Shoes({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M3.6 15.6c0-2 1.4-3.1 4-3.5 2.6-.4 4.8-1.4 6.2-3 .8-.9 1.4-1.8 2.6-2 1.6-.3 2.8 1.2 3.2 3.6.3 1.6.6 3.3 1 4.9v.8q0 1.6-1.6 1.6H5.2q-1.6 0-1.6-1.6Z"/><path d="M3.6 15.6h17"/>
    </svg>
  );
}

/** shorts — shorts, short, bottoms, summer */
export function Shorts({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M5.8 6.6h12.4l.8 10.8h-4.8l-1.4-5Q12 10.9 11.2 12.4l-1.4 5H5Z"/><path d="M5.7 9.2h12.6"/>
    </svg>
  );
}

/** sock — sock, socks, hosiery */
export function Sock({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M6.6 3.8H12v8.6c0 1.4.8 2.2 2.2 2.8 2.2.9 3.6 1.9 3.6 3.3s-1.2 2.1-3 2.1h-4c-2.6 0-4.2-1.8-4.2-4.4Z"/><path d="M6.6 6.8H12"/>
    </svg>
  );
}

/** sort — order, arrange, rank, sequence */
export function Sort({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M4.4 6.9h8.6"/><path d="M4.4 12h5.7"/><path d="M4.4 17.1h3.1"/><path d="M16.9 6.3v11.4"/><path d="m14.2 15 2.7 2.7 2.7-2.7"/>
    </svg>
  );
}

/** sparkle — sparkle */
export function Sparkle({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M9.65 3.65Q10.65 2.75 11.65 3.65Q12.59 8.86 17.8 9.8Q18.7 10.8 17.8 11.8Q12.59 12.74 11.65 17.95Q10.65 18.85 9.65 17.95Q8.71 12.74 3.5 11.8Q2.6 10.8 3.5 9.8Q8.71 8.86 9.65 3.65Z"/><path d="M17.5 15.27Q18 14.83 18.5 15.27Q19.06 16.99 20.78 17.55Q21.22 18.05 20.78 18.55Q19.06 19.11 18.5 20.83Q18 21.27 17.5 20.83Q16.94 19.11 15.22 18.55Q14.78 18.05 15.22 17.55Q16.94 16.99 17.5 15.27Z"/>
    </svg>
  );
}

/** spring — spring */
export function Spring({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M12 20.7v-6.1"/><path d="M12 14.6Q4.5 14.4 5.9 7 13.4 7.3 12 14.6Z"/><path d="M12 14.6Q19.5 14.4 18.1 7 10.6 7.3 12 14.6Z"/>
    </svg>
  );
}

/** star-dollar — credits, star, dollar, reward, balance */
export function StarDollar({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M10.44 4.76Q12 2.2 13.56 4.76L14.27 5.94Q15.44 7.87 17.63 8.38L18.97 8.7Q21.89 9.39 19.93 11.66L19.03 12.7Q17.56 14.41 17.75 16.65L17.86 18.02Q18.11 21.01 15.35 19.85L14.07 19.32Q12 18.45 9.93 19.32L8.65 19.85Q5.89 21.01 6.14 18.02L6.25 16.65Q6.44 14.41 4.97 12.7L4.07 11.66Q2.11 9.39 5.03 8.7L6.37 8.38Q8.56 7.87 9.73 5.94Z"/><path d="M13.9 8.2H11.6a1.8 1.8 0 0 0 0 3.6h.8a1.8 1.8 0 0 1 0 3.6H10.1"/><path d="M12 7v9.6"/>
    </svg>
  );
}

/** storefront — shop, marketplace, store, sell */
export function Storefront({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M4.4 9.8h15.2v8.4a1.8 1.8 0 0 1-1.8 1.8H6.2a1.8 1.8 0 0 1-1.8-1.8Z"/><path d="M5.6 4.4h12.8l1.6 5.4H4Z"/><path d="M9.6 20v-4.6h4.8V20"/>
    </svg>
  );
}

/** suitcase — suitcase */
export function Suitcase({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.2" y="7.5" width="17.6" height="12.6" rx="3.5"/><path d="M8.8 7.5V6a1.7 1.7 0 0 1 1.7-1.7h3a1.7 1.7 0 0 1 1.7 1.7v1.5"/><path d="M9.3 11.3v5"/><path d="M14.7 11.3v5"/>
    </svg>
  );
}

/** summer — summer */
export function Summer({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="12" cy="12" r="3.8"/><path d="M12 5.4V3.1"/><path d="M12 18.6v2.3"/><path d="M18.6 12h2.3"/><path d="M5.4 12H3.1"/><path d="m16.67 7.33 1.62-1.62"/><path d="m7.33 16.67-1.62 1.62"/><path d="m16.67 16.67 1.62 1.62"/><path d="m7.33 7.33-1.62-1.62"/>
    </svg>
  );
}

/** sweater — sweater, jumper, hoodie, knit, pullover */
export function Sweater({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M9.4 6.4 5.4 8l-1.1 7.8 2.7.8 1-5.6v8.5h8V11l1 5.6 2.7-.8L18.6 8l-4-1.6a2.6 2.6 0 0 1-5.2 0Z"/><path d="M8 17.6h8"/>
    </svg>
  );
}

/** tag — tag */
export function Tag({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M11.6 3.6H6.6A3 3 0 0 0 3.6 6.6v5l7.6 7.6a2.6 2.6 0 0 0 3.68 0l4.3-4.3a2.6 2.6 0 0 0 0-3.68Z"/><circle cx="7.4" cy="7.4" r="1" fill="currentColor" stroke="none"/>
    </svg>
  );
}

/** thermometer — thermometer */
export function Thermometer({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M12.4 14.67V5.9a1.7 1.7 0 0 0-3.4 0v8.77a3.3 3.3 0 1 0 3.4 0Z"/><circle cx="10.7" cy="17.5" r=".85" fill="currentColor" stroke="none"/><path d="M15.6 9.2h2.6"/><path d="M15.6 12.4h2.6"/>
    </svg>
  );
}

/** top — top, shirt, tee, t-shirt, tshirt */
export function Top({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M7.6 5.4 3.6 9.2l2.4 2.6 1.6-1.6v9Q7.6 20.6 9.2 20.6h5.6q1.6 0 1.6-1.6v-9l1.6 1.6 2.4-2.6-4-3.8h-2.1a2.5 2.5 0 0 1-4.6 0Z"/>
    </svg>
  );
}

/** trash — delete, remove, bin, discard */
export function Trash({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M4.4 6.7h15.2"/><path d="M9 6.7V5.65a1.7 1.7 0 0 1 1.7-1.7h2.6a1.7 1.7 0 0 1 1.7 1.7V6.7"/><path d="m6.5 6.7.78 11.2a2.2 2.2 0 0 0 2.2 2.05h5.04a2.2 2.2 0 0 0 2.2-2.05L17.5 6.7"/>
    </svg>
  );
}

/** upload — import, add, send, attach */
export function Upload({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M12 13.8V3.9"/><path d="m8.5 7.4 3.5-3.5 3.5 3.5"/><path d="M4.5 15.8v1.9a2.5 2.5 0 0 0 2.5 2.5h10a2.5 2.5 0 0 0 2.5-2.5v-1.9"/>
    </svg>
  );
}

/** user — user */
export function User({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="12" cy="7.9" r="3.85"/><path d="M5 20.5a7.1 7.1 0 0 1 14 0"/>
    </svg>
  );
}

/** wallet — wallet, money, spend, cash, payment */
export function Wallet({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <rect x="3.4" y="5.9" width="17.2" height="13" rx="3.7"/><path d="M20.6 9.7h-4.4a2.7 2.7 0 1 0 0 5.4h4.4"/><circle cx="17.1" cy="12.4" r=".85" fill="currentColor" stroke="none"/>
    </svg>
  );
}

/** watch — watch, wristwatch, time, accessory */
export function Watch({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <circle cx="12" cy="12.4" r="4.3"/><path d="m9.9 8.7.2-3.5a1.3 1.3 0 0 1 1.3-1.2h1.2a1.3 1.3 0 0 1 1.3 1.2l.2 3.5"/><path d="m9.9 16.1.2 3.5a1.3 1.3 0 0 0 1.3 1.2h1.2a1.3 1.3 0 0 0 1.3-1.2l.2-3.5"/><path d="M16.5 12.4h1.2"/><path d="M12 10.3v2.1h1.7"/>
    </svg>
  );
}

/** wind — wind */
export function Wind({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M12.9 18.7A1.8 1.8 0 1 0 14 15.5H3.4"/><path d="M16.9 8.4a2.2 2.2 0 1 1 1.8 3.6H3.4"/><path d="M10.1 5.2A1.8 1.8 0 1 1 11.2 8.5H3.4"/>
    </svg>
  );
}

/** winter — winter */
export function Winter({ size = 20, ...props }: IconProps) {
  return (
    <svg {...BASE} width={size} height={size} aria-hidden focusable="false" {...props}>
      <path d="M3.6 12h16.8"/><path d="M12 3.6v16.8"/><path d="m17.9 15.2-3.2-3.2 3.2-3.2"/><path d="m6.1 8.8 3.2 3.2-3.2 3.2"/><path d="m15.2 6.1-3.2 3.2-3.2-3.2"/><path d="m8.8 17.9 3.2-3.2 3.2 3.2"/>
    </svg>
  );
}

/** Every icon, for the gallery and for name-based lookup. */
export const ICON_REGISTRY: readonly {
  name: string;
  keywords: readonly string[];
  Component: (props: IconProps) => JSX.Element;
}[] = [
  { name: "bag", keywords: ["bag", "handbag", "tote", "purse"], Component: Bag },
  { name: "brand-facebook", keywords: ["facebook", "meta", "fb"], Component: BrandFacebook },
  { name: "brand-pinterest", keywords: ["pinterest", "pin"], Component: BrandPinterest },
  { name: "brand-reddit", keywords: ["reddit", "snoo", "forum"], Component: BrandReddit },
  { name: "brand-whatsapp", keywords: ["whatsapp", "chat", "message"], Component: BrandWhatsapp },
  { name: "brand-x", keywords: ["twitter", "x", "tweet"], Component: BrandX },
  { name: "budget", keywords: ["budget", "gauge", "meter", "remaining", "limit"], Component: Budget },
  { name: "calendar", keywords: ["calendar"], Component: Calendar },
  { name: "camera", keywords: ["camera"], Component: Camera },
  { name: "chart", keywords: ["chart"], Component: Chart },
  { name: "check", keywords: ["done", "tick", "confirm", "complete"], Component: Check },
  { name: "clock", keywords: ["clock"], Component: Clock },
  { name: "close", keywords: ["x", "dismiss", "cancel", "clear"], Component: Close },
  { name: "closet", keywords: ["closet"], Component: Closet },
  { name: "cloud", keywords: ["cloud"], Component: Cloud },
  { name: "coins", keywords: ["coins", "money", "cash", "currency", "savings"], Component: Coins },
  { name: "download", keywords: ["save", "export", "get", "get-file"], Component: Download },
  { name: "dress", keywords: ["dress", "gown", "frock"], Component: Dress },
  { name: "edit", keywords: ["pencil", "write", "rename", "modify"], Component: Edit },
  { name: "external-link", keywords: ["buy", "shop", "open", "outbound", "link"], Component: ExternalLink },
  { name: "eye", keywords: ["eye"], Component: Eye },
  { name: "fall", keywords: ["fall"], Component: Fall },
  { name: "filter", keywords: ["funnel", "refine", "narrow", "facets"], Component: Filter },
  { name: "gear", keywords: ["gear"], Component: Gear },
  { name: "glasses", keywords: ["glasses", "spectacles", "eyewear", "sunglasses"], Component: Glasses },
  { name: "grid", keywords: ["grid"], Component: Grid },
  { name: "hanger", keywords: ["hanger"], Component: Hanger },
  { name: "hat", keywords: ["hat", "cap", "headwear"], Component: Hat },
  { name: "heart", keywords: ["heart"], Component: Heart },
  { name: "link", keywords: ["url", "chain", "copy link"], Component: Link },
  { name: "list", keywords: ["list"], Component: List },
  { name: "mail", keywords: ["email", "envelope", "message"], Component: Mail },
  { name: "outerwear", keywords: ["outerwear", "coat", "jacket", "overcoat"], Component: Outerwear },
  { name: "palette", keywords: ["palette"], Component: Palette },
  { name: "pants", keywords: ["pants", "trousers", "jeans", "bottoms"], Component: Pants },
  { name: "piggy-bank", keywords: ["savings", "piggy", "bank", "save", "money"], Component: PiggyBank },
  { name: "plus", keywords: ["add", "new", "create", "plus"], Component: Plus },
  { name: "price-drop", keywords: ["sale", "discount", "price", "markdown", "tag"], Component: PriceDrop },
  { name: "rain", keywords: ["rain"], Component: Rain },
  { name: "receipt", keywords: ["receipt", "purchase", "invoice", "bill", "order"], Component: Receipt },
  { name: "refresh", keywords: ["reload", "sync", "retry", "update"], Component: Refresh },
  { name: "ruler", keywords: ["ruler"], Component: Ruler },
  { name: "scan", keywords: ["scan"], Component: Scan },
  { name: "search", keywords: ["find", "magnifier", "lookup", "browse"], Component: Search },
  { name: "share", keywords: ["send", "network", "refer", "invite"], Component: Share },
  { name: "shoes", keywords: ["shoes", "sneaker", "footwear", "trainers"], Component: Shoes },
  { name: "shorts", keywords: ["shorts", "short", "bottoms", "summer"], Component: Shorts },
  { name: "sock", keywords: ["sock", "socks", "hosiery"], Component: Sock },
  { name: "sort", keywords: ["order", "arrange", "rank", "sequence"], Component: Sort },
  { name: "sparkle", keywords: ["sparkle"], Component: Sparkle },
  { name: "spring", keywords: ["spring"], Component: Spring },
  { name: "star-dollar", keywords: ["credits", "star", "dollar", "reward", "balance"], Component: StarDollar },
  { name: "storefront", keywords: ["shop", "marketplace", "store", "sell"], Component: Storefront },
  { name: "suitcase", keywords: ["suitcase"], Component: Suitcase },
  { name: "summer", keywords: ["summer"], Component: Summer },
  { name: "sweater", keywords: ["sweater", "jumper", "hoodie", "knit", "pullover"], Component: Sweater },
  { name: "tag", keywords: ["tag"], Component: Tag },
  { name: "thermometer", keywords: ["thermometer"], Component: Thermometer },
  { name: "top", keywords: ["top", "shirt", "tee", "t-shirt", "tshirt"], Component: Top },
  { name: "trash", keywords: ["delete", "remove", "bin", "discard"], Component: Trash },
  { name: "upload", keywords: ["import", "add", "send", "attach"], Component: Upload },
  { name: "user", keywords: ["user"], Component: User },
  { name: "wallet", keywords: ["wallet", "money", "spend", "cash", "payment"], Component: Wallet },
  { name: "watch", keywords: ["watch", "wristwatch", "time", "accessory"], Component: Watch },
  { name: "wind", keywords: ["wind"], Component: Wind },
  { name: "winter", keywords: ["winter"], Component: Winter },
];

export type IconName = (typeof ICON_REGISTRY)[number]["name"];
